CREATE TABLE RECIPES (
  RECIPE_ID int(10) NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  DESCRIPTION varchar(255) DEFAULT NULL,
  PRIMARY KEY (RECIPE_ID)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8;


CREATE TABLE INGREDIENTS (
  INGREDIENT_ID int(10) NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  PRIMARY KEY (INGREDIENT_ID)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8;

CREATE TABLE RECIPES_INGREDIENTS (
  RECIPE_ID int(10) NOT NULL,
  INGREDIENT_ID int(10) NOT NULL,
  QUANTITY  DECIMAL(10,2) NOT NULL,
  UNIT VARCHAR(10) NOT NULL,

  PRIMARY KEY (RECIPE_ID,INGREDIENT_ID),
  CONSTRAINT FK_RECIPES_INGREDIENTS_RECIPES FOREIGN KEY (RECIPE_ID) REFERENCES RECIPES (RECIPE_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_RECIPES_INGREDIENTS_INGREDIENTS FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENTS (INGREDIENT_ID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
