CREATE TABLE recipes (
  RECIPE_ID int(10) NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  DESCRIPTION varchar(255) DEFAULT NULL,
  PRIMARY KEY (RECIPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE ingredients (
  INGREDIENT_ID int(10) NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  PRIMARY KEY (INGREDIENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE recipes_ingredients (
  RECIPE_ID int(10) NOT NULL,
  INGREDIENT_ID int(10) NOT NULL,
  QUANTITY  DECIMAL(10,2) NOT NULL,
  UNIT VARCHAR(10) NOT NULL,

  PRIMARY KEY (RECIPE_ID,INGREDIENT_ID),
  CONSTRAINT FK_RECIPES_INGREDIENTS_RECIPES FOREIGN KEY (RECIPE_ID) REFERENCES recipes (RECIPE_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_RECIPES_INGREDIENTS_INGREDIENTS FOREIGN KEY (INGREDIENT_ID) REFERENCES ingredients (INGREDIENT_ID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
